# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Peca.create([{nome: 'Memória', caracteristica: '2 GB'}])

Modelo.create([{marca: 'HP Probook 6470B', configuracao: '1. Peso: 2,27 Kg 2. Sistema Operacional: MS-Windows 7 Professional, em português do Brasil; acompanhado de licença de uso. 3. Requisitos ofertados: Microprocessador (com dissipador e cooler adequados) com frequência de 2,6GHz e cache de 3MB L3 com arquitetura quatro núcleos; Processador Intel Core i5-3320M; 04 GB de Memória SDRAM-DDR3- frequência1333MHZ, expansível a 8GB e tela de 14” LED- antirreflexo. 4. Conectores: 04 USB 2.0; 01 RJ-45; 01 Microfone (entrada); 01 Fone de ouvido (saída); 01 Saída VGA para Monitor Externo;01 Conector Displayport; 01 Conector para entrada de Energia - AC power. 5. Unidades de Armazenamento: 01 (uma) unidade de disco rígido, SATA de 500 GB de 7200 rpm; Sistema de proteção de dados: redução da transmissão de impactos e vibração ao disco rígido, durante o uso normal; 01 unidade de DVD+/-RW SATA interna ao gabinete. 6. Acessórios: maleta do mesmo fabricante com todos os cabos de alimentação e interconexão do equipamento; Adaptador AC; Bateria de Íon de Lítio de 6 células com autonomia de até 8h 15 min; mouse óptico USB; possui slot Express Card, Bluetooth, Webcam e Adaptador Displayport HDMI.', valor: '3300', tipo: 'Notebook'}])
Modelo.create([{marca: 'HP Probook 4320S', configuracao: 'Peso: 2,0 Kg. com as seguintes descrição técnica: 1. Requisitos ofertados: - FSB (Front Side Bus) de 1066MHz; Microprocessador (com dissipador e cooler adequados) com frequência de 2,26GHz e cache de 3MB L3 com arquitetura de núcleo duplo; Processador Intel Core i3-350M; 03 GB de Memória SDRAM-DDR3-frequência 1333MHZ, expansível a, no mínimo, 8GB. 2. Conectores: - 03 USB 2.0; 01 RJ-45; 01 RJ-II; 01 Microphone (entrada); 01 Fone de ouvido (saida); 01 Saída VGA para Monitor Externo; 01 Conector Bateria entrada Energia -AC power. 3. Unidades de Armazenamento: - 01 (uma) unidade de disco rígido, Smart SATA de 250 GB nominal e 5400 rpm; Sistema de proteção de dados: redução da transmissão de impactos e vibração ao disco rígido, durante o uso normal; 01 Unidade de DVD/RW integrada ao equipamento. 4. Acessórios: - está acompanhado de maleta do mesmo fabricante com todos os cabos de alimentação e interconexão do equipamento; Cabo de alimentação; Adaptador AC; Cabo do modem; Bateria de Lithium-Ion 6-cell com autonomia de 4,5 horas; possui slot Kensington e Webcam. 5. Sistema Operacional MS-Windows XP Professional pré-instalado, em português do Brasil; acompanhado de licença de uso.', valor: '2652', tipo: 'Notebook'}])
Modelo.create([{marca: 'HP Probook 4430S', configuracao: '1 . Peso: 2,0 Kg 2. Sistema Operacional: MS-Windows 7 Professional pré-instalado, em português do Brasil; acompanhado de licença de uso. 3. Requisitos ofertados: FSB (Front Side Bus) de 1066MHz; Microprocessador (com dissipador e cooler adequados) com frequência de 2,66GHz e cache de 8MB L3 com arquitetura quatro núcleos; Processador Intel Core i5-2540M; 04 GB de Memória SDRAM-DDR3- frequência1333MHZ, expansível a, no mínimo, 8GB e tela de 14”. 4. Conectores: - 03 USB 2.0; 01 USB 3.0; 01 RJ-45; 01 Microfone (entrada); 01 Fone de ouvido (saída); 01 Saída VGA para Monitor Externo; 01 Conector Bateria entrada Energia - AC power. 5. Unidades de Armazenamento: - 01 (uma) unidade de disco rígido, Smart SATA de 320 GB nominal e 5400 rpm; Sistema de proteção de dados: redução da transmissão de impactos e vibração ao disco rígido, durante o uso normal; 01 unidade de Bluray (combo) integrada ao equipamento. 6. Acessórios: - maleta do mesmo fabricante com todos os cabos de alimentação e interconexão do equipamento; Cabo de alimentação; Adaptador AC; Cabo do modem; Bateria de Lithium-Ion 6-cell com autonomia de 4,5 horas; possui slot Kensington e Webcam.', valor: '2600', tipo: 'Notebook'}])

Servidor.create([{siape: '1971282', nome: 'Adriano de Almeida Ferraiuoli', telefone: '(22)99973-9376', email: 'adriano.ferraioli@iff.edu.br', status: 'Ativo', cargo: 'Docente'}])
Servidor.create([{siape: '1506445', nome: 'Rodrigo Garrett da Costa', telefone: '(22)99701-6280', email: 'rgarrett@iff.edu.br', status: 'Ativo', cargo: 'Docente'}])
Servidor.create([{siape: '6269223', nome: 'Carlos Alberto de Oliveira Guimarães', telefone: '(22)99983-1424', email: 'cguimaraes@iff.edu.br', status: 'Ativo', cargo: 'Docente'}])